# Generated by Django 6.0.3 on 2026-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciso_assistant', '0008_add_compliance_gap_source_choice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source_type'], name='ciso_assist_source__0c122c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['framework'], name='ciso_assist_framewo_8b7bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['control_code'], name='ciso_assist_control_e05f72_idx'),
        ),
    ]
