# Generated by Django 6.0.3 on 2026-05-15 23:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciso_assistant', '0009_knowledgechunk_ciso_assist_source__0c122c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagIngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('incremental', 'Incremental'), ('full', 'Completa')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Concluída'), ('failed', 'Falhada')], default='running', max_length=20)),
                ('triggered_by_label', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('chunks_created', models.IntegerField(default=0)),
                ('chunks_updated', models.IntegerField(default=0)),
                ('chunks_removed', models.IntegerField(default=0)),
                ('chunks_failed', models.IntegerField(default=0)),
                ('total_processed', models.IntegerField(default=0)),
                ('counts_by_type', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, help_text='Fatal error that aborted the run')),
                ('error_detail', models.TextField(blank=True, help_text='Per-item indexing failures')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='ciso_assist_status_4ac021_idx'), models.Index(fields=['-started_at'], name='ciso_assist_started_569d26_idx')],
            },
        ),
    ]
