# Generated by Django 6.0.3 on 2026-05-17 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciso_assistant', '0010_ragingestionrun'),
        ('governance', '0020_alter_decisionrecord_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('task_type', models.CharField(blank=True, max_length=100)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('used_rag', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sources_json', models.JSONField(blank=True, default=list)),
                ('history_json', models.JSONField(blank=True, default=list)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('created_by_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_recommendations', to='governance.decisionrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ciso_assist_created_5079fd_idx'), models.Index(fields=['task_type'], name='ciso_assist_task_ty_bae4ef_idx'), models.Index(fields=['used_rag'], name='ciso_assist_used_ra_892821_idx')],
            },
        ),
    ]
