# Generated by Django 6.0.3 on 2026-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciso_assistant', '0011_assistantrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='source_type',
            field=models.CharField(choices=[('policy', 'Policy'), ('asset', 'Asset'), ('vulnerability', 'Vulnerability'), ('control', 'Control'), ('mechanism', 'Mechanism'), ('technical_regulation', 'Technical Regulation'), ('procedure', 'Procedure'), ('evidence', 'Evidence'), ('compliance_gap', 'Compliance Gap'), ('internal_control', 'Internal Control'), ('governance_document', 'Governance Document'), ('governance_section', 'Governance Document Section'), ('evidence_item', 'Evidence Item'), ('framework_mapping', 'Internal Control Framework Mapping'), ('internal_control_mechanism', 'Internal Control Mechanism'), ('general', 'General Knowledge')], max_length=50),
        ),
    ]
