# Generated by Django 5.2.7 on 2026-02-22 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(default='Portugal', max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('main_email', models.EmailField(blank=True, max_length=254)),
                ('main_phone', models.CharField(blank=True, max_length=40)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
