# Generated by Django 6.0.3 on 2026-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyprofile_nis2_subsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='nis2_sector',
            field=models.CharField(choices=[('none', 'Setor nÃ£o abrangido'), ('annex1_energy', 'Anexo I - Energia'), ('annex1_transport', 'Anexo I - Transportes'), ('annex1_banking', 'Anexo I - Banca'), ('annex1_fin_infra', 'Anexo I - Infraestruturas do Mercado Financeiro'), ('annex1_health', 'Anexo I - SaÃºde'), ('annex1_water', 'Anexo I - Ã\x81gua PotÃ¡vel'), ('annex1_waste_water', 'Anexo I - Ã\x81guas Residuais'), ('annex1_dig_infra', 'Anexo I - Infraestrutura Digital'), ('annex1_ict_mgmt', 'Anexo I - GestÃ£o de ServiÃ§os de TIC (B2B)'), ('annex1_pub_admin', 'Anexo I - AdministraÃ§Ã£o PÃºblica'), ('annex1_space', 'Anexo I - EspaÃ§o'), ('annex2_postal', 'Anexo II - ServiÃ§os Postais e de Estafeta'), ('annex2_waste_mgmt', 'Anexo II - GestÃ£o de ResÃ\xadduos'), ('annex2_chem', 'Anexo II - Fabrico, ProduÃ§Ã£o e DistribuiÃ§Ã£o de Produtos QuÃ\xadmicos'), ('annex2_food', 'Anexo II - ProduÃ§Ã£o, TransformaÃ§Ã£o e DistribuiÃ§Ã£o de Alimentos'), ('annex2_mfg', 'Anexo II - Fabrico (Maquinaria, VeÃ\xadculos, Equipamentos)'), ('annex2_dig_prov', 'Anexo II - Fornecedores Digitais (Marketplaces, Motores de Busca, Redes Sociais)'), ('annex2_research', 'Anexo II - OrganizaÃ§Ãµes de InvestigaÃ§Ã£o')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nis2_subsector',
            field=models.CharField(blank=True, choices=[('electricity', 'Eletricidade'), ('district_heating', 'Aquecimento/Arrefecimento Urbano'), ('oil', 'PetrÃ³leo'), ('gas', 'GÃ¡s'), ('hydrogen', 'HidrogÃ©nio'), ('air', 'Transporte AÃ©reo'), ('rail', 'Transporte FerroviÃ¡rio'), ('water', 'Transporte por Vias NavegÃ¡veis'), ('road', 'Transporte RodoviÃ¡rio'), ('credit_inst', 'InstituiÃ§Ãµes de CrÃ©dito'), ('trading_venue', 'Operadores de Plataformas de NegociaÃ§Ã£o'), ('ccp', 'Contrapartes Centrais'), ('healthcare_prov', 'Prestadores de Cuidados de SaÃºde'), ('eu_ref_lab', 'LaboratÃ³rios de ReferÃªncia da UE'), ('pharma_r_d', 'InvestigaÃ§Ã£o e Desenvolvimento de Medicamentos'), ('pharma_mfg', 'Fabrico de Produtos FarmacÃªuticos'), ('med_device_mfg', 'Fabrico de Dispositivos MÃ©dicos'), ('water_supply', 'Abastecimento e DistribuiÃ§Ã£o de Ã\x81gua'), ('waste_water_coll', 'Recolha e Tratamento de Ã\x81guas Residuais'), ('ixp', 'Pontos de Troca de TrÃ¡fego Internet (IXP)'), ('dns', 'Sistemas de Nomes de DomÃ\xadnio (DNS)'), ('tld', 'Registos de Nomes de DomÃ\xadnio de Topo (TLD)'), ('cloud', 'ServiÃ§os de ComputaÃ§Ã£o em Nuvem'), ('data_centre', 'ServiÃ§os de Centro de Dados'), ('cdn', 'Redes de DÃ©bito de ConteÃºdo (CDN)'), ('trust_service', 'ServiÃ§os de ConfianÃ§a'), ('elec_comm', 'Redes/ServiÃ§os de ComunicaÃ§Ãµes EletrÃ³nicas PÃºblicas'), ('msp', 'Managed Service Providers (MSP)'), ('mssp', 'Managed Security Service Providers (MSSP)'), ('central_gov', 'AdministraÃ§Ã£o Central'), ('regional_gov', 'AdministraÃ§Ã£o Regional'), ('space_ops', 'Operadores de Infraestruturas Terrestres (EspaÃ§o)'), ('postal_services', 'ServiÃ§os Postais e de Estafeta'), ('waste_coll', 'Recolha, Transporte e GestÃ£o de ResÃ\xadduos'), ('chem_mfg', 'Fabrico de Produtos QuÃ\xadmicos'), ('food_prod', 'ProduÃ§Ã£o, TransformaÃ§Ã£o e DistribuiÃ§Ã£o de Alimentos'), ('mfg_med_devices', 'Fabrico de Dispositivos MÃ©dicos (Geral)'), ('mfg_comp_elec', 'Fabrico de Produtos InformÃ¡ticos e EletrÃ³nicos'), ('mfg_elec_eq', 'Fabrico de Equipamentos ElÃ©tricos'), ('mfg_machinery', 'Fabrico de MÃ¡quinas e Equipamentos'), ('mfg_vehicles', 'Fabrico de VeÃ\xadculos AutomÃ³veis'), ('mfg_transport_eq', 'Fabrico de Outro Equipamento de Transporte'), ('online_mkt', 'Mercados em Linha (Marketplaces)'), ('search_engine', 'Motores de Busca em Linha'), ('social_net', 'Redes Sociais'), ('research_org', 'Organismos de InvestigaÃ§Ã£o / Universidades')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='org_type',
            field=models.CharField(choices=[('Public', 'PÃºblica'), ('Private', 'Privada'), ('ThirdSector', 'Terceiro Setor')], default='Private', max_length=50),
        ),
    ]
