# Generated by Django 6.0.3 on 2026-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyprofile_nis2_subsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='nis2_sector',
            field=models.CharField(choices=[('none', 'Setor não abrangido'), ('annex1_energy', 'Anexo I - Energia'), ('annex1_transport', 'Anexo I - Transportes'), ('annex1_banking', 'Anexo I - Banca'), ('annex1_fin_infra', 'Anexo I - Infraestruturas do Mercado Financeiro'), ('annex1_health', 'Anexo I - Saúde'), ('annex1_water', 'Anexo I - Ã\x81gua Potável'), ('annex1_waste_water', 'Anexo I - Ã\x81guas Residuais'), ('annex1_dig_infra', 'Anexo I - Infraestrutura Digital'), ('annex1_ict_mgmt', 'Anexo I - Gestão de Serviços de TIC (B2B)'), ('annex1_pub_admin', 'Anexo I - Administração Pública'), ('annex1_space', 'Anexo I - Espaço'), ('annex2_postal', 'Anexo II - Serviços Postais e de Estafeta'), ('annex2_waste_mgmt', 'Anexo II - Gestão de ResÃ\xadduos'), ('annex2_chem', 'Anexo II - Fabrico, Produção e Distribuição de Produtos QuÃ\xadmicos'), ('annex2_food', 'Anexo II - Produção, Transformação e Distribuição de Alimentos'), ('annex2_mfg', 'Anexo II - Fabrico (Maquinaria, VeÃ\xadculos, Equipamentos)'), ('annex2_dig_prov', 'Anexo II - Fornecedores Digitais (Marketplaces, Motores de Busca, Redes Sociais)'), ('annex2_research', 'Anexo II - Organizações de Investigação')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nis2_subsector',
            field=models.CharField(blank=True, choices=[('electricity', 'Eletricidade'), ('district_heating', 'Aquecimento/Arrefecimento Urbano'), ('oil', 'Petróleo'), ('gas', 'Gás'), ('hydrogen', 'Hidrogénio'), ('air', 'Transporte Aéreo'), ('rail', 'Transporte Ferroviário'), ('water', 'Transporte por Vias Navegáveis'), ('road', 'Transporte Rodoviário'), ('credit_inst', 'Instituições de Crédito'), ('trading_venue', 'Operadores de Plataformas de Negociação'), ('ccp', 'Contrapartes Centrais'), ('healthcare_prov', 'Prestadores de Cuidados de Saúde'), ('eu_ref_lab', 'Laboratórios de Referência da UE'), ('pharma_r_d', 'Investigação e Desenvolvimento de Medicamentos'), ('pharma_mfg', 'Fabrico de Produtos Farmacêuticos'), ('med_device_mfg', 'Fabrico de Dispositivos Médicos'), ('water_supply', 'Abastecimento e Distribuição de Ã\x81gua'), ('waste_water_coll', 'Recolha e Tratamento de Ã\x81guas Residuais'), ('ixp', 'Pontos de Troca de Tráfego Internet (IXP)'), ('dns', 'Sistemas de Nomes de DomÃ\xadnio (DNS)'), ('tld', 'Registos de Nomes de DomÃ\xadnio de Topo (TLD)'), ('cloud', 'Serviços de Computação em Nuvem'), ('data_centre', 'Serviços de Centro de Dados'), ('cdn', 'Redes de Débito de Conteúdo (CDN)'), ('trust_service', 'Serviços de Confiança'), ('elec_comm', 'Redes/Serviços de Comunicações Eletrónicas Públicas'), ('msp', 'Managed Service Providers (MSP)'), ('mssp', 'Managed Security Service Providers (MSSP)'), ('central_gov', 'Administração Central'), ('regional_gov', 'Administração Regional'), ('space_ops', 'Operadores de Infraestruturas Terrestres (Espaço)'), ('postal_services', 'Serviços Postais e de Estafeta'), ('waste_coll', 'Recolha, Transporte e Gestão de ResÃ\xadduos'), ('chem_mfg', 'Fabrico de Produtos QuÃ\xadmicos'), ('food_prod', 'Produção, Transformação e Distribuição de Alimentos'), ('mfg_med_devices', 'Fabrico de Dispositivos Médicos (Geral)'), ('mfg_comp_elec', 'Fabrico de Produtos Informáticos e Eletrónicos'), ('mfg_elec_eq', 'Fabrico de Equipamentos Elétricos'), ('mfg_machinery', 'Fabrico de Máquinas e Equipamentos'), ('mfg_vehicles', 'Fabrico de VeÃ\xadculos Automóveis'), ('mfg_transport_eq', 'Fabrico de Outro Equipamento de Transporte'), ('online_mkt', 'Mercados em Linha (Marketplaces)'), ('search_engine', 'Motores de Busca em Linha'), ('social_net', 'Redes Sociais'), ('research_org', 'Organismos de Investigação / Universidades')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='org_type',
            field=models.CharField(choices=[('Public', 'Pública'), ('Private', 'Privada'), ('ThirdSector', 'Terceiro Setor')], default='Private', max_length=50),
        ),
    ]
