# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyprofile_nis2_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='onboarding_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='onboarding_recommended_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='preferred_frameworks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='primary_security_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='risk_appetite',
            field=models.CharField(
                choices=[
                    ('conservative', 'Conservador'),
                    ('balanced', 'Equilibrado'),
                    ('tolerant', 'Tolerante'),
                ],
                default='balanced',
                max_length=30,
            ),
        ),
    ]
