# Generated by Django 6.0.3 on 2026-05-17 15:40

from django.db import migrations


def _column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }


def relax_legacy_columns(apps, schema_editor):
    """
    Migration 0008 copied data from the legacy `role_type` / `department_id`
    columns into `role` / `org_unit_id` but left the originals NOT NULL with no
    default, which blocked every new Person insert. The Person model no longer
    maps them, so drop the NOT NULL constraint to unblock inserts. Data is kept.
    """
    person = apps.get_model("company", "Person")
    table = person._meta.db_table
    qn = schema_editor.connection.ops.quote_name
    columns = _column_names(schema_editor, table)
    for legacy in ("role_type", "department_id"):
        if legacy in columns:
            schema_editor.execute(
                f"ALTER TABLE {qn(table)} ALTER COLUMN {qn(legacy)} DROP NOT NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_companyprofile_nis2_sector_and_more'),
    ]

    operations = [
        migrations.RunPython(relax_legacy_columns, migrations.RunPython.noop),
    ]
