# Generated by Django 6.0.3 on 2026-05-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_relax_legacy_person_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='critical_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='is_security_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to='company.person'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='security_relevance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='unit_type',
            field=models.CharField(choices=[('board', 'Administracao'), ('business', 'Negocio'), ('it', 'Tecnologia'), ('security', 'Seguranca'), ('operations', 'Operacoes'), ('support', 'Suporte'), ('external', 'Externo'), ('other', 'Outro')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='backup_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='company.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='governance_role',
            field=models.CharField(choices=[('ciso', 'CISO'), ('security_officer', 'Security Officer'), ('it_owner', 'IT Owner'), ('risk_owner', 'Risk Owner'), ('business_owner', 'Business Owner'), ('data_protection', 'Data Protection'), ('compliance_owner', 'Compliance Owner'), ('policy_owner', 'Policy Owner'), ('auditor', 'Auditor'), ('executive_sponsor', 'Executive Sponsor'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='is_security_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
