# Generated by Django 6.0.3 on 2026-05-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_repair_legacy_networkrange_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='availability',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_value',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3, help_text='Valor do ativo para o negócio'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='confidentiality',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='criticality',
            field=models.CharField(choices=[('Critical', 'Crítico (5)'), ('High', 'Alto (4)'), ('Medium', 'Médio (3)'), ('Low', 'Baixo (2)'), ('Very Low', 'Muito Baixo (1)')], db_index=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='dependency_score',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3, help_text='Nível de dependência de outros ativos'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exposure',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='importance',
            field=models.CharField(choices=[('Critical', 'Crítico (5)'), ('High', 'Alto (4)'), ('Medium', 'Médio (3)'), ('Low', 'Baixo (2)'), ('Very Low', 'Muito Baixo (1)')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='integrity',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Localização física ou lógica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.assetlocation'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(choices=[('very_low', 'Muito Baixo'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Elevado'), ('critical', 'Crítico')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='overall_level',
            field=models.CharField(choices=[('very_low', 'Muito Baixo'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Elevado'), ('critical', 'Crítico')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='status',
            field=models.CharField(choices=[('planned', 'Planeado'), ('in_progress', 'Em Curso'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='availability',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='business_value',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='confidentiality',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='criticality',
            field=models.CharField(choices=[('Critical', 'Crítico (5)'), ('High', 'Alto (4)'), ('Medium', 'Médio (3)'), ('Low', 'Baixo (2)'), ('Very Low', 'Muito Baixo (1)')], db_index=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='dependency_score',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='exposure',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
        migrations.AlterField(
            model_name='software',
            name='integrity',
            field=models.SmallIntegerField(choices=[(1, 'Muito Baixo (1)'), (2, 'Baixo (2)'), (3, 'Médio (3)'), (4, 'Alto (4)'), (5, 'Crítico (5)')], default=3),
        ),
    ]
