# Generated by Django 6.0.3 on 2026-05-24 23:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_alter_asset_availability_alter_asset_business_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('nmap', 'Nmap'), ('wazuh', 'Wazuh'), ('manual', 'Manual'), ('import', 'Import')], db_index=True, default='nmap', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='queued', max_length=20)),
                ('target_scope', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('ignored_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_discovery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDiscoveryFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('os_name', models.CharField(blank=True, max_length=255)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('vulnerabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('duplicate', 'Duplicate'), ('merged', 'Merged')], db_index=True, default='new', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('match_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_findings', to='risk.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_asset_discovery_findings', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='risk.assetdiscoveryrun')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetExposureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(db_index=True, default='nmap', max_length=30)),
                ('exposure_score', models.PositiveSmallIntegerField(default=3)),
                ('exposure_label', models.CharField(blank=True, max_length=100)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('vulnerabilities_summary', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_snapshots', to='risk.asset')),
                ('discovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposure_snapshots', to='risk.assetdiscoveryrun')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetClassificationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('validated', 'Validated'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('classification_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criticality_at_review', models.CharField(blank=True, max_length=50)),
                ('confidentiality', models.PositiveSmallIntegerField(default=3)),
                ('integrity', models.PositiveSmallIntegerField(default=3)),
                ('availability', models.PositiveSmallIntegerField(default=3)),
                ('exposure', models.PositiveSmallIntegerField(default=3)),
                ('business_value', models.PositiveSmallIntegerField(default=3)),
                ('dependency_score', models.PositiveSmallIntegerField(default=3)),
                ('rationale', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='risk.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_classification_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_asset_classification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_current', '-created_at'],
                'indexes': [models.Index(fields=['asset', 'is_current'], name='ix_asset_class_current'), models.Index(fields=['status'], name='ix_asset_class_status'), models.Index(fields=['next_review_at'], name='ix_asset_class_next_review')],
            },
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryrun',
            index=models.Index(fields=['source', 'status'], name='ix_asset_run_source_status'),
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryrun',
            index=models.Index(fields=['started_at'], name='ix_asset_run_started_at'),
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryfinding',
            index=models.Index(fields=['status'], name='ix_asset_finding_status'),
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryfinding',
            index=models.Index(fields=['ip_address'], name='ix_asset_finding_ip'),
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryfinding',
            index=models.Index(fields=['hostname'], name='ix_asset_finding_host'),
        ),
        migrations.AddIndex(
            model_name='assetexposuresnapshot',
            index=models.Index(fields=['asset', 'captured_at'], name='ix_asset_exposure_asset_time'),
        ),
        migrations.AddIndex(
            model_name='assetexposuresnapshot',
            index=models.Index(fields=['source'], name='ix_asset_exposure_source'),
        ),
    ]
