# Generated by Django 6.0.3 on 2026-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_assetdiscoveryrun_assetdiscoveryfinding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclassificationreview',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('draft', 'Draft'), ('pending_review', 'Pending review'), ('validated', 'Validated'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='incomplete', max_length=20),
        ),
    ]
