# Generated by Codex on 2026-05-31

import django.utils.timezone
import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_vulnerability_kev_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[
                            ('explainable_weighted', 'Ponderado explicavel'),
                            ('xgboost_shap', 'XGBoost + SHAP interno'),
                        ],
                        default='explainable_weighted',
                        max_length=40,
                    ),
                ),
                ('feature_store_enabled', models.BooleanField(default=True)),
                ('shadow_mode_enabled', models.BooleanField(default=False)),
                ('min_labeled_outcomes', models.PositiveIntegerField(default=200)),
                ('min_review_cycles', models.PositiveSmallIntegerField(default=2)),
                ('active_model_version', models.CharField(blank=True, max_length=80)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('holdout_auc', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('holdout_brier', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('last_training_summary', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do modelo de priorizacao',
                'verbose_name_plural': 'Configuracoes do modelo de priorizacao',
            },
        ),
        migrations.CreateModel(
            name='PriorityFeatureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_key', models.CharField(db_index=True, max_length=80)),
                ('asset_key', models.CharField(blank=True, max_length=80)),
                ('vulnerability_key', models.CharField(blank=True, max_length=80)),
                ('observed_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('model_mode', models.CharField(default='explainable_weighted', max_length=40)),
                ('estimator_key', models.CharField(default='weighted_v1', max_length=60)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('score_snapshot', models.JSONField(blank=True, default=dict)),
                ('contribution_breakdown', models.JSONField(blank=True, default=list)),
                ('priority_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('remediation_score', models.FloatField(default=0.0)),
                ('outcome_status', models.CharField(blank=True, max_length=40)),
                (
                    'outcome_label',
                    models.CharField(
                        choices=[
                            ('open', 'Aberto'),
                            ('in_remediation', 'Em remediacao'),
                            ('remediated', 'Remediado'),
                            ('accepted_risk', 'Risco aceite'),
                            ('false_positive', 'Falso positivo'),
                            ('unknown', 'Desconhecido'),
                        ],
                        default='unknown',
                        max_length=60,
                    ),
                ),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='priority_feature_snapshots',
                        to='risk.asset',
                    ),
                ),
                (
                    'occurrence',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='priority_feature_snapshots',
                        to='risk.assetvulnerability',
                    ),
                ),
                (
                    'vulnerability',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='priority_feature_snapshots',
                        to='risk.vulnerability',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Snapshot de features de priorizacao',
                'verbose_name_plural': 'Snapshots de features de priorizacao',
            },
        ),
        migrations.AddIndex(
            model_name='priorityfeaturesnapshot',
            index=models.Index(fields=['model_mode', 'observed_on'], name='risk_priori_model_m_c446ff_idx'),
        ),
        migrations.AddIndex(
            model_name='priorityfeaturesnapshot',
            index=models.Index(fields=['outcome_label', 'observed_on'], name='risk_priori_outcome_3593b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='priorityfeaturesnapshot',
            constraint=models.UniqueConstraint(
                fields=('occurrence_key', 'observed_on', 'model_mode'),
                name='unique_priority_snapshot_per_day',
            ),
        ),
    ]
