# Generated by Django 6.0.3 on 2026-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wazuh', 'Wazuh'), ('epss', 'FIRST EPSS'), ('nist', 'NIST NVD'), ('nmap', 'Nmap Discovery (SSH)')], help_text='The name of the external service provider.', max_length=50, unique=True)),
                ('api_url', models.CharField(blank=True, help_text='The base URL or Hostname for the API (e.g. Manager API).', max_length=255, null=True)),
                ('indexer_url', models.CharField(blank=True, help_text='The base URL or Hostname for the Wazuh Indexer.', max_length=255, null=True)),
                ('indexer_username', models.CharField(blank=True, help_text='The username for the Wazuh Indexer.', max_length=255, null=True)),
                ('indexer_password', models.CharField(blank=True, help_text='The password for the Wazuh Indexer.', max_length=255, null=True)),
                ('username', models.CharField(blank=True, help_text='Username for API authentication.', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='Password or token for API authentication.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Integration Sync Status',
                'verbose_name_plural': 'Integration Sync Statuses',
                'unique_together': {('provider', 'sync_type')},
            },
        ),
    ]
