# Generated by Django 5.2.7 on 2026-02-22 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('domain', 'Domain'), ('tech', 'Tech'), ('reg', 'Reg')], default='domain', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('ISO27001', 'ISO/IEC 27001'), ('NISTCSF', 'NIST CSF'), ('QNRC', 'QNRC')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('source_uri', models.URLField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'version'], name='ix_framework_code_version')],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uq_framework_code_version')],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('implementation_guidance', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('applicability_scope', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='governance.framework')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('baseline', 'Baseline'), ('target', 'Target'), ('regulatory', 'Regulatory')], default='baseline', max_length=100)),
                ('maturity_model', models.CharField(blank=True, max_length=100)),
                ('max_level', models.PositiveSmallIntegerField(default=5)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='governance.framework')),
            ],
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('implementation_status', models.CharField(choices=[('not_started', 'Not started'), ('planned', 'Planned'), ('partial', 'Partial'), ('implemented', 'Implemented'), ('optimized', 'Optimized')], default='not_started', max_length=20)),
                ('maturity_level', models.PositiveSmallIntegerField(default=0)),
                ('effectiveness', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('risk_inherent', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('risk_residual', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.CharField(blank=True, max_length=150)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='governance.control')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='governance.frameworkprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='governance.framework')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='governance.frameworksection')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='governance.frameworksection'),
        ),
        migrations.CreateModel(
            name='ImprovementAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('plan', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='governance.controlassessment')),
            ],
        ),
        migrations.CreateModel(
            name='ControlTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tags', to='governance.control')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_tags', to='governance.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ControlMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('supports', 'Supports'), ('conflicts', 'Conflicts')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('rationale', models.TextField(blank=True)),
                ('source_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_out', to='governance.control')),
                ('target_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_in', to='governance.control')),
            ],
            options={
                'indexes': [models.Index(fields=['source_control'], name='ix_mapping_source'), models.Index(fields=['target_control'], name='ix_mapping_target')],
                'constraints': [models.UniqueConstraint(fields=('source_control', 'target_control', 'mapping_type'), name='uq_mapping_src_tgt_type'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_mapping_conf_0_1'), models.CheckConstraint(condition=models.Q(('source_control', models.F('target_control')), _negated=True), name='ck_mapping_no_self')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('log', 'Log'), ('screenshot', 'Screenshot'), ('ticket', 'Ticket'), ('config', 'Config')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=2048)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='governance.controlassessment')),
            ],
            options={
                'indexes': [models.Index(fields=['assessment', 'evidence_type'], name='ix_evidence_assessment_type')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=15)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='governance.controlassessment')),
            ],
            options={
                'indexes': [models.Index(fields=['assessment', 'severity'], name='ix_finding_assessment_sev'), models.Index(fields=['status'], name='ix_finding_status')],
            },
        ),
        migrations.AddIndex(
            model_name='frameworkprofile',
            index=models.Index(fields=['framework', 'name'], name='ix_profile_fw_name'),
        ),
        migrations.AddConstraint(
            model_name='frameworkprofile',
            constraint=models.UniqueConstraint(fields=('framework', 'name'), name='uq_profile_framework_name'),
        ),
        migrations.AddConstraint(
            model_name='frameworkprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_level__gte', 1), ('max_level__lte', 20)), name='ck_profile_maxlevel_1_20'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['profile', 'implementation_status'], name='ix_assessment_profile_status'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['control'], name='ix_assessment_control'),
        ),
        migrations.AddConstraint(
            model_name='controlassessment',
            constraint=models.UniqueConstraint(fields=('profile', 'control'), name='uq_assessment_profile_control'),
        ),
        migrations.AddConstraint(
            model_name='controlassessment',
            constraint=models.CheckConstraint(condition=models.Q(('maturity_level__gte', 0)), name='ck_assessment_maturity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='controlassessment',
            constraint=models.CheckConstraint(condition=models.Q(('effectiveness__gte', 0), ('effectiveness__lte', 1)), name='ck_assessment_eff_0_1'),
        ),
        migrations.AddConstraint(
            model_name='controlassessment',
            constraint=models.CheckConstraint(condition=models.Q(('risk_inherent__gte', 0), ('risk_inherent__lte', 1)), name='ck_assessment_rin_0_1'),
        ),
        migrations.AddConstraint(
            model_name='controlassessment',
            constraint=models.CheckConstraint(condition=models.Q(('risk_residual__gte', 0), ('risk_residual__lte', 1)), name='ck_assessment_rres_0_1'),
        ),
        migrations.AddIndex(
            model_name='frameworksection',
            index=models.Index(fields=['framework', 'level', 'sort_order'], name='ix_section_fw_level_sort'),
        ),
        migrations.AddIndex(
            model_name='frameworksection',
            index=models.Index(fields=['framework', 'code'], name='ix_section_fw_code'),
        ),
        migrations.AddConstraint(
            model_name='frameworksection',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uq_section_framework_code'),
        ),
        migrations.AddConstraint(
            model_name='frameworksection',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='ck_section_level_gte_1'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['framework', 'code'], name='ix_control_fw_code'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['section'], name='ix_control_section'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uq_control_framework_code'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['assessment', 'status'], name='ix_action_assessment_status'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['due_date'], name='ix_action_due_date'),
        ),
        migrations.AddIndex(
            model_name='controltag',
            index=models.Index(fields=['tag'], name='ix_controltag_tag'),
        ),
        migrations.AddConstraint(
            model_name='controltag',
            constraint=models.UniqueConstraint(fields=('control', 'tag'), name='uq_control_tag'),
        ),
    ]
