# Generated by Django 5.2.7 on 2026-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_framework_description_framework_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='publisher',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
