# Generated by Django 5.2.7 on 2026-03-03 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_framework_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='governance.framework')),
            ],
        ),
        migrations.AddField(
            model_name='frameworksection',
            name='level_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='governance.frameworklevel'),
        ),
        migrations.AddIndex(
            model_name='frameworklevel',
            index=models.Index(fields=['framework', 'level'], name='ix_level_fw_level'),
        ),
        migrations.AddConstraint(
            model_name='frameworklevel',
            constraint=models.UniqueConstraint(fields=('framework', 'level'), name='uq_level_framework_level'),
        ),
        migrations.AddConstraint(
            model_name='frameworklevel',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='ck_level_level_gte_1'),
        ),
    ]
