# Generated by Django 6.0.3 on 2026-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0018_decisionrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['code'], 'verbose_name': 'Política de Segurança', 'verbose_name_plural': 'Políticas de Segurança'},
        ),
        migrations.AlterModelOptions(
            name='policysection',
            options={'ordering': ['order'], 'verbose_name': 'Secção de Política', 'verbose_name_plural': 'Secções de Política'},
        ),
        migrations.AlterField(
            model_name='policycontrol',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20),
        ),
    ]
