# Generated by Django 6.0.3 on 2026-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0019_alter_policy_options_alter_policysection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionrecord',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('mitigate', 'Mitigate'), ('transferred', 'Transferred'), ('converted_to_action', 'Converted to Action')], default='deferred', max_length=30),
        ),
    ]
