# Generated by Django 6.0.3 on 2026-05-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_orgunit_critical_services_and_more'),
        ('governance', '0020_alter_decisionrecord_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='accountable_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_policies', to='company.person'),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to='company.orgunit'),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to='company.person'),
        ),
    ]
