# Generated by Django 6.0.3 on 2026-05-17 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0021_policy_accountable_person_policy_owner_org_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('control_domain', models.CharField(blank=True, max_length=150)),
                ('objective', models.TextField(blank=True)),
                ('risk_statement', models.TextField(blank=True)),
                ('owner_role', models.CharField(blank=True, max_length=150)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_controls', to='governance.control')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InternalControlFrameworkMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('supports', 'Supports'), ('overlaps', 'Overlaps'), ('derived', 'Derived')], default='partial', max_length=20)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_control_mappings', to=settings.AUTH_USER_MODEL)),
                ('framework_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_mappings', to='governance.control')),
                ('internal_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='governance.internalcontrol')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_internal_control_mappings', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_internal_control_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['internal_control__code', 'framework_control__framework__code', 'framework_control__code'],
            },
        ),
        migrations.AddIndex(
            model_name='internalcontrol',
            index=models.Index(fields=['code'], name='ix_internal_control_code'),
        ),
        migrations.AddIndex(
            model_name='internalcontrol',
            index=models.Index(fields=['status'], name='ix_internal_control_status'),
        ),
        migrations.AddIndex(
            model_name='internalcontrol',
            index=models.Index(fields=['source'], name='ix_internal_control_source'),
        ),
        migrations.AddIndex(
            model_name='internalcontrol',
            index=models.Index(fields=['control_domain'], name='ix_internal_control_domain'),
        ),
        migrations.AddIndex(
            model_name='internalcontrol',
            index=models.Index(fields=['is_active'], name='ix_internal_control_active'),
        ),
        migrations.AddIndex(
            model_name='internalcontrolframeworkmapping',
            index=models.Index(fields=['internal_control'], name='ix_icfm_internal_control'),
        ),
        migrations.AddIndex(
            model_name='internalcontrolframeworkmapping',
            index=models.Index(fields=['framework_control'], name='ix_icfm_framework_control'),
        ),
        migrations.AddIndex(
            model_name='internalcontrolframeworkmapping',
            index=models.Index(fields=['relationship_type'], name='ix_icfm_relationship'),
        ),
        migrations.AddIndex(
            model_name='internalcontrolframeworkmapping',
            index=models.Index(fields=['mapping_source'], name='ix_icfm_source'),
        ),
        migrations.AddIndex(
            model_name='internalcontrolframeworkmapping',
            index=models.Index(fields=['validation_status'], name='ix_icfm_validation'),
        ),
        migrations.AddConstraint(
            model_name='internalcontrolframeworkmapping',
            constraint=models.UniqueConstraint(fields=('internal_control', 'framework_control'), name='uq_internal_control_framework_control'),
        ),
        migrations.AddConstraint(
            model_name='internalcontrolframeworkmapping',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_percentage__gte', 0), ('coverage_percentage__lte', 100)), name='ck_icfm_coverage_0_100'),
        ),
        migrations.AddConstraint(
            model_name='internalcontrolframeworkmapping',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='ck_icfm_confidence_0_100'),
        ),
    ]
