# Generated by Django 6.0.3 on 2026-05-17 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0022_internalcontrol_internalcontrolframeworkmapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyInternalControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicability', models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('not_applicable', 'Not applicable')], default='mandatory', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_internal_controls', to=settings.AUTH_USER_MODEL)),
                ('internal_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_links', to='governance.internalcontrol')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_links', to='governance.policy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policy_internal_controls', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_policy_internal_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy__code', 'internal_control__code'],
                'indexes': [models.Index(fields=['policy'], name='ix_pic_policy'), models.Index(fields=['internal_control'], name='ix_pic_internal_control'), models.Index(fields=['applicability'], name='ix_pic_applicability'), models.Index(fields=['mapping_source'], name='ix_pic_source'), models.Index(fields=['validation_status'], name='ix_pic_validation')],
                'constraints': [models.UniqueConstraint(fields=('policy', 'internal_control'), name='uq_policy_internal_control'), models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='ck_pic_confidence_0_100')],
            },
        ),
    ]
