# Generated by Django 6.0.3 on 2026-05-17 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0023_policyinternalcontrol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalControlMechanism',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_weight', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('mandatory', models.BooleanField(default=False)),
                ('relationship_type', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting'), ('compensating', 'Compensating'), ('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], default='supporting', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_control_mechanisms', to=settings.AUTH_USER_MODEL)),
                ('internal_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanism_links', to='governance.internalcontrol')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_control_links', to='governance.mechanism')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_internal_control_mechanisms', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_internal_control_mechanisms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['internal_control__code', 'mechanism__title'],
                'indexes': [models.Index(fields=['internal_control'], name='ix_icm_internal_control'), models.Index(fields=['mechanism'], name='ix_icm_mechanism'), models.Index(fields=['relationship_type'], name='ix_icm_relationship'), models.Index(fields=['mandatory'], name='ix_icm_mandatory'), models.Index(fields=['mapping_source'], name='ix_icm_source'), models.Index(fields=['validation_status'], name='ix_icm_validation')],
                'constraints': [models.UniqueConstraint(fields=('internal_control', 'mechanism'), name='uq_internal_control_mechanism'), models.CheckConstraint(condition=models.Q(('contribution_weight__gte', 0), ('contribution_weight__lte', 100)), name='ck_icm_weight_0_100'), models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='ck_icm_confidence_0_100')],
            },
        ),
    ]
