# Generated by Django 6.0.3 on 2026-05-17 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0024_internalcontrolmechanism'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('standard', 'Standard'), ('procedure', 'Procedure'), ('guideline', 'Guideline'), ('technical_regulation', 'Technical regulation'), ('runbook', 'Runbook')], default='policy', max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_documents', to='governance.policy')),
                ('legacy_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_documents', to='governance.procedure')),
                ('legacy_technical_regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_documents', to='governance.technicalregulation')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='governance.governancedocument')),
            ],
            options={
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceDocumentControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('defines', 'Defines'), ('implements', 'Implements'), ('operationalizes', 'Operationalizes'), ('evidences', 'Evidences')], default='defines', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_document_controls', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_links', to='governance.governancedocument')),
                ('internal_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='governance.internalcontrol')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_governance_document_controls', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_governance_document_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document__title', 'internal_control__code', 'purpose'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceDocumentSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='governance.governancedocument')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='governance.governancedocumentsection')),
            ],
            options={
                'ordering': ['document__title', 'order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='RunbookStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('evidence_required', models.BooleanField(default=False)),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbook_steps', to='governance.governancedocument')),
            ],
            options={
                'ordering': ['runbook__title', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['document_type'], name='ix_gdoc_type'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['status'], name='ix_gdoc_status'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['owner'], name='ix_gdoc_owner'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['parent_document'], name='ix_gdoc_parent'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['is_active'], name='ix_gdoc_active'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentcontrol',
            index=models.Index(fields=['document'], name='ix_gdc_document'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentcontrol',
            index=models.Index(fields=['internal_control'], name='ix_gdc_internal'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentcontrol',
            index=models.Index(fields=['purpose'], name='ix_gdc_purpose'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentcontrol',
            index=models.Index(fields=['mapping_source'], name='ix_gdc_source'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentcontrol',
            index=models.Index(fields=['validation_status'], name='ix_gdc_validation'),
        ),
        migrations.AddConstraint(
            model_name='governancedocumentcontrol',
            constraint=models.UniqueConstraint(fields=('document', 'internal_control', 'purpose'), name='uq_gdoc_control_purpose'),
        ),
        migrations.AddConstraint(
            model_name='governancedocumentcontrol',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='ck_gdc_confidence_0_100'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentsection',
            index=models.Index(fields=['document'], name='ix_gdsec_document'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentsection',
            index=models.Index(fields=['parent_section'], name='ix_gdsec_parent'),
        ),
        migrations.AddIndex(
            model_name='governancedocumentsection',
            index=models.Index(fields=['order'], name='ix_gdsec_order'),
        ),
        migrations.AddIndex(
            model_name='runbookstep',
            index=models.Index(fields=['runbook'], name='ix_runbook_step_doc'),
        ),
        migrations.AddIndex(
            model_name='runbookstep',
            index=models.Index(fields=['step_number'], name='ix_runbook_step_no'),
        ),
        migrations.AddConstraint(
            model_name='runbookstep',
            constraint=models.UniqueConstraint(fields=('runbook', 'step_number'), name='uq_runbook_step_number'),
        ),
    ]
