# Generated by Django 6.0.3 on 2026-05-17 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('governance', '0025_governancedocument_governancedocumentcontrol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('report', 'Report'), ('screenshot', 'Screenshot'), ('ticket', 'Ticket'), ('log', 'Log'), ('audit_report', 'Audit report'), ('configuration_export', 'Configuration export'), ('meeting_minutes', 'Meeting minutes'), ('approval_record', 'Approval record'), ('vulnerability_scan', 'Vulnerability scan'), ('siem_alert', 'SIEM alert'), ('manual_attestation', 'Manual attestation'), ('other', 'Other')], default='other', max_length=30)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence_items/')),
                ('external_reference', models.CharField(blank=True, max_length=2048)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('valid', 'Valid'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='governance.evidence')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('internal_control', 'Internal control'), ('mechanism', 'Mechanism'), ('governance_document', 'Governance document'), ('runbook_step', 'Runbook step'), ('framework_control', 'Framework control'), ('policy', 'Policy'), ('risk', 'Risk'), ('asset', 'Asset'), ('vulnerability', 'Vulnerability'), ('finding', 'Finding'), ('improvement_action', 'Improvement action')], max_length=40)),
                ('target_id', models.UUIDField()),
                ('link_type', models.CharField(choices=[('evidences', 'Evidences'), ('supports', 'Supports'), ('validates', 'Validates'), ('demonstrates', 'Demonstrates'), ('mitigates', 'Mitigates'), ('justifies', 'Justifies'), ('produced_by', 'Produced by'), ('required_by', 'Required by')], default='evidences', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_source', models.CharField(choices=[('manual', 'Manual'), ('migrated', 'Migrated'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested'), ('rule_based', 'Rule based'), ('template', 'Template')], default='manual', max_length=20)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='governance.evidenceitem')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_links', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_evidence_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['evidence_item__title', 'target_type', 'link_type'],
            },
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['evidence_type'], name='ix_eitem_type'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['status'], name='ix_eitem_status'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['owner'], name='ix_eitem_owner'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['valid_until'], name='ix_eitem_valid_until'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['is_active'], name='ix_eitem_active'),
        ),
        migrations.AddConstraint(
            model_name='evidenceitem',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__gte', 0), ('confidence_level__lte', 100)), name='ck_eitem_confidence_0_100'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['evidence_item'], name='ix_elink_evidence'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['target_type', 'target_id'], name='ix_elink_target'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['link_type'], name='ix_elink_link_type'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['mapping_source'], name='ix_elink_source'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['validation_status'], name='ix_elink_validation'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.UniqueConstraint(fields=('evidence_item', 'target_type', 'target_id', 'link_type'), name='uq_evidence_link_target_type'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), name='ck_elink_confidence_0_100'),
        ),
    ]
