# Generated by Django 6.0.3 on 2026-05-17 22:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0026_evidenceitem_evidencelink_evidenceitem_ix_eitem_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePropagationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('mechanism', 'Mechanism'), ('internal_control', 'Internal control'), ('policy', 'Policy'), ('governance_document', 'Governance document'), ('framework_control', 'Framework control'), ('framework', 'Framework'), ('domain', 'Domain')], max_length=30)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('not_assessed', 'Not assessed'), ('non_compliant', 'Non compliant'), ('partially_compliant', 'Partially compliant'), ('mostly_compliant', 'Mostly compliant'), ('compliant', 'Compliant'), ('not_applicable', 'Not applicable')], default='not_assessed', max_length=30)),
                ('calculation_mode', models.CharField(choices=[('official', 'Official'), ('simulation', 'Simulation'), ('exploratory', 'Exploratory')], default='official', max_length=20)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-calculated_at', 'result_type', 'target_type'],
                'indexes': [models.Index(fields=['result_type'], name='ix_cpr_result_type'), models.Index(fields=['target_type', 'target_id'], name='ix_cpr_target'), models.Index(fields=['calculation_mode'], name='ix_cpr_mode'), models.Index(fields=['status'], name='ix_cpr_status'), models.Index(fields=['calculated_at'], name='ix_cpr_calculated_at')],
                'constraints': [models.UniqueConstraint(fields=('result_type', 'target_type', 'target_id', 'calculation_mode'), name='uq_compliance_propagation_result')],
            },
        ),
    ]
