# Generated by Django 6.0.3 on 2026-05-18 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0027_compliancepropagationresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcontrolmechanism',
            name='implementation_status',
            field=models.CharField(choices=[('not_implemented', 'Not implemented'), ('planned', 'Planned'), ('partially_implemented', 'Partially implemented'), ('implemented', 'Implemented'), ('implemented_evidenced', 'Implemented evidenced'), ('not_applicable', 'Not applicable')], default='not_implemented', max_length=30),
        ),
        migrations.AddIndex(
            model_name='internalcontrolmechanism',
            index=models.Index(fields=['implementation_status'], name='ix_icm_impl_status'),
        ),
    ]
