# Generated by Django 6.0.3 on 2026-05-22 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0028_internalcontrolmechanism_implementation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanismEvidenceRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('report', 'Report'), ('screenshot', 'Screenshot'), ('ticket', 'Ticket'), ('log', 'Log'), ('audit_report', 'Audit report'), ('configuration_export', 'Configuration export'), ('meeting_minutes', 'Meeting minutes'), ('approval_record', 'Approval record'), ('vulnerability_scan', 'Vulnerability scan'), ('siem_alert', 'SIEM alert'), ('manual_attestation', 'Manual attestation'), ('other', 'Other')], default='report', max_length=30)),
                ('mechanism_type', models.CharField(blank=True, max_length=50)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('control_domain', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('template', 'Template'), ('rule_based', 'Rule based'), ('imported', 'Imported'), ('ai_suggested', 'AI suggested')], default='template', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mechanism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='governance.mechanism')),
            ],
            options={
                'ordering': ['priority', 'title'],
                'indexes': [models.Index(fields=['mechanism'], name='ix_mevreq_mechanism'), models.Index(fields=['evidence_type'], name='ix_mevreq_type'), models.Index(fields=['mechanism_type'], name='ix_mevreq_mech_type'), models.Index(fields=['control_domain'], name='ix_mevreq_domain'), models.Index(fields=['priority'], name='ix_mevreq_priority'), models.Index(fields=['source'], name='ix_mevreq_source'), models.Index(fields=['is_active'], name='ix_mevreq_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mechanism__isnull', False)), fields=('mechanism', 'title', 'evidence_type'), name='uq_mech_evidence_req_specific'), models.UniqueConstraint(condition=models.Q(('mechanism__isnull', True)), fields=('title', 'evidence_type', 'mechanism_type', 'control_domain'), name='uq_mech_evidence_req_template')],
            },
        ),
    ]
