# Generated by Django 6.0.3 on 2026-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0029_mechanismevidencerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionrecord',
            name='action_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionrecord',
            name='compliance_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionrecord',
            name='evidence_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionrecord',
            name='responsible',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='decisionrecord',
            name='risk_impact',
            field=models.TextField(blank=True),
        ),
    ]
