# Generated by Django 6.0.3 on 2026-05-23 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0030_decisionrecord_action_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('policy_exception', 'Policy exception'), ('control_exception', 'Control exception'), ('risk_acceptance', 'Risk acceptance'), ('implementation_delay', 'Implementation delay'), ('compensating_control', 'Compensating control')], default='risk_acceptance', max_length=40)),
                ('target_type', models.CharField(choices=[('policy', 'Policy'), ('internal_control', 'Internal control'), ('framework_control', 'Framework control'), ('mechanism', 'Mechanism'), ('internal_control_mechanism', 'Internal control mechanism'), ('governance_document', 'Governance document'), ('risk', 'Risk'), ('asset', 'Asset'), ('vulnerability', 'Vulnerability')], max_length=40)),
                ('target_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('business_justification', models.TextField(blank=True)),
                ('compensating_control_description', models.TextField(blank=True)),
                ('risk_impact', models.TextField(blank=True)),
                ('compliance_impact', models.TextField(blank=True)),
                ('score_impact', models.DecimalField(decimal_places=2, default=0, help_text='Estimated impact in percentage points. Negative values reduce the adjusted score.', max_digits=6)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('approver', models.CharField(blank=True, max_length=255)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('evidence_reference', models.TextField(blank=True)),
                ('action_reference', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_governance_exceptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_exceptions', to=settings.AUTH_USER_MODEL)),
                ('linked_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_exceptions', to='governance.decisionrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_governance_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exception_type'], name='ix_gov_exc_type'), models.Index(fields=['target_type', 'target_id'], name='ix_gov_exc_target'), models.Index(fields=['approval_status'], name='ix_gov_exc_status'), models.Index(fields=['valid_until'], name='ix_gov_exc_valid_until'), models.Index(fields=['owner'], name='ix_gov_exc_owner')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score_impact__gte', -100), ('score_impact__lte', 100)), name='ck_gov_exc_score_impact')],
            },
        ),
    ]
