# Generated by Django 6.0.3 on 2026-05-23 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0031_governanceexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('correct_policy', 'Correct policy'), ('map_control', 'Map control'), ('implement_mechanism', 'Implement mechanism'), ('collect_evidence', 'Collect evidence'), ('review_document', 'Review document'), ('approve_mapping', 'Approve mapping'), ('update_framework', 'Update framework'), ('review_exception', 'Review exception'), ('review_score', 'Review score'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('workbench', 'Workbench'), ('compliance_gap', 'Compliance gap'), ('ai_recommendation', 'AI recommendation'), ('score', 'Score'), ('exception', 'Exception')], default='manual', max_length=40)),
                ('source_key', models.CharField(blank=True, max_length=120)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('score_impact', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_governance_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_actions', to=settings.AUTH_USER_MODEL)),
                ('linked_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_actions', to='governance.decisionrecord')),
                ('linked_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_actions', to='governance.governanceexception')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_governance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='ix_gov_action_status_prio'), models.Index(fields=['action_type'], name='ix_gov_action_type'), models.Index(fields=['due_date'], name='ix_gov_action_due'), models.Index(fields=['source_type', 'source_key'], name='ix_gov_action_source'), models.Index(fields=['target_type', 'target_id'], name='ix_gov_action_target'), models.Index(fields=['owner'], name='ix_gov_action_owner')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score_impact__gte', -100), ('score_impact__lte', 100)), name='ck_gov_action_score_impact'), models.UniqueConstraint(condition=models.Q(models.Q(('source_key', ''), _negated=True), models.Q(('status__in', ['done', 'cancelled']), _negated=True)), fields=('source_type', 'source_key'), name='uq_gov_action_active_source')],
            },
        ),
    ]
