# Generated by Codex on 2026-05-24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0033_governanceaction_operational_planning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceRiskLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("internal_control", "Internal control"),
                            ("mechanism", "Mechanism"),
                            ("internal_control_mechanism", "Internal control mechanism"),
                            ("policy", "Policy"),
                            ("governance_document", "Governance document"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_id", models.CharField(max_length=100)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("risk", "Risk"),
                            ("asset", "Asset"),
                            ("vulnerability", "Vulnerability"),
                            ("asset_vulnerability", "Asset vulnerability"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_id", models.CharField(max_length=100)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("mitigates", "Mitigates"),
                            ("reduces_likelihood", "Reduces likelihood"),
                            ("reduces_impact", "Reduces impact"),
                            ("detects", "Detects"),
                            ("prevents", "Prevents"),
                            ("compensates", "Compensates"),
                            ("monitors", "Monitors"),
                        ],
                        default="mitigates",
                        max_length=40,
                    ),
                ),
                (
                    "effectiveness_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Estimated effectiveness of the governance source in this risk context.",
                        max_digits=5,
                    ),
                ),
                (
                    "residual_impact_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated percentage reduction contribution to residual risk.",
                        max_digits=5,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "mapping_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("migrated", "Migrated"),
                            ("imported", "Imported"),
                            ("ai_suggested", "AI suggested"),
                            ("rule_based", "Rule based"),
                            ("template", "Template"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_governance_risk_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_governance_risk_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_governance_risk_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["target_type", "target_id", "source_type", "source_id"],
                "indexes": [
                    models.Index(fields=["source_type", "source_id"], name="ix_grl_source"),
                    models.Index(fields=["target_type", "target_id"], name="ix_grl_target"),
                    models.Index(fields=["relationship_type"], name="ix_grl_relation"),
                    models.Index(fields=["mapping_source"], name="ix_grl_source_type"),
                    models.Index(fields=["validation_status"], name="ix_grl_validation"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_type",
                            "source_id",
                            "target_type",
                            "target_id",
                            "relationship_type",
                        ),
                        name="uq_governance_risk_link",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effectiveness_percentage__gte", 0), ("effectiveness_percentage__lte", 100)),
                        name="ck_grl_effectiveness_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("residual_impact_percentage__gte", 0), ("residual_impact_percentage__lte", 100)),
                        name="ck_grl_residual_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence_score__gte", 0), ("confidence_score__lte", 100)),
                        name="ck_grl_confidence_0_100",
                    ),
                ],
            },
        ),
    ]
