# Generated by Django 6.0.3 on 2026-05-25 21:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0034_governancerisklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAssessmentSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('baseline', 'Baseline'), ('audit', 'Audit'), ('manual', 'Manual'), ('system', 'System'), ('demo', 'Demo')], default='manual', max_length=20)),
                ('snapshot_label', models.CharField(blank=True, max_length=180)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('implementation_status', models.CharField(choices=[('not_started', 'Not started'), ('planned', 'Planned'), ('partial', 'Partial'), ('implemented', 'Implemented'), ('optimized', 'Optimized')], max_length=20)),
                ('maturity_level', models.PositiveSmallIntegerField(default=0)),
                ('effectiveness', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('risk_inherent', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('risk_residual', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(blank=True, default='control_assessment', max_length=80)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='governance.controlassessment')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshots', to='governance.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_assessment_snapshots', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshots', to='governance.frameworkprofile')),
            ],
            options={
                'ordering': ['-captured_at', 'control__framework__code', 'control__code'],
                'indexes': [models.Index(fields=['assessment', 'captured_at'], name='ix_ca_snapshot_assessment_time'), models.Index(fields=['control', 'captured_at'], name='ix_ca_snapshot_control_time'), models.Index(fields=['profile', 'captured_at'], name='ix_ca_snapshot_profile_time'), models.Index(fields=['snapshot_type'], name='ix_ca_snapshot_type')],
            },
        ),
    ]
