# Generated by Django 6.0.3 on 2026-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0035_controlassessmentsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('onboarding', 'Onboarding'), ('workbench', 'Workbench'), ('compliance_gap', 'Compliance gap'), ('ai_recommendation', 'AI recommendation'), ('score', 'Score'), ('exception', 'Exception')], default='manual', max_length=40),
        ),
    ]
